language: r
cache: packages

fortran: true

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars
    
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - g++-7
      
after_success:
  - Rscript -e 'covr::codecov()'

matrix:
  include:
    - os: linux
      r: release
      sudo : false
    - os: linux
      r: devel
      sudo : false
    - os: osx
      latex: false
      r: devel
    - os: osx
      latex: false
      r: release
  allow_failures:
    - os: osx

global:
  - _R_CHECK_FORCE_SUGGESTS_: false
  
