# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RInterface <- function(x, y, n_models, h, t, u, tolerance, max_iter, initial_split, neighborhood_search, neighborhood_search_tolerance) {
    .Call('_RMSS_RInterface', PACKAGE = 'RMSS', x, y, n_models, h, t, u, tolerance, max_iter, initial_split, neighborhood_search, neighborhood_search_tolerance)
}

RInterfaceCV <- function(x, y, n_models, h, t, u, tolerance, max_iter, initial_split_array, initial_split, neighborhood_search, neighborhood_search_tolerance, n_folds, cv_criterion, alpha, gamma, n_threads) {
    .Call('_RMSS_RInterfaceCV', PACKAGE = 'RMSS', x, y, n_models, h, t, u, tolerance, max_iter, initial_split_array, initial_split, neighborhood_search, neighborhood_search_tolerance, n_folds, cv_criterion, alpha, gamma, n_threads)
}

